<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-26A9125" failures="3" tests="3" name="Test" time="48.118" errors="0" timestamp="2024-01-31T01:16:53 IST">
  <testcase classname="TestCases.TC_001_Test_AccountReg" name="verifyaccountregistration" time="12.194">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at TestCases.TC_001_Test_AccountReg.verifyaccountregistration(TC_001_Test_AccountReg.java:46)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyaccountregistration -->
  <testcase classname="TestCases.TC_002_TestLogin" name="verify_login" time="5.057">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at TestCases.TC_002_TestLogin.verify_login(TC_002_TestLogin.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verify_login -->
  <testcase classname="TestCases.TC_003_TestLoginDataDrivenTesting" name="verify_loginddt" time="0.0">
    <failure type="org.testng.TestNGException" message="
Method public void TestCases.TC_003_TestLoginDataDrivenTesting.verify_loginddt(java.lang.String,java.lang.String,java.lang.String) requires a @DataProvider named : logindata in class Utilities.DataProviders">
      <![CDATA[org.testng.TestNGException: 
Method public void TestCases.TC_003_TestLoginDataDrivenTesting.verify_loginddt(java.lang.String,java.lang.String,java.lang.String) requires a @DataProvider named : logindata in class Utilities.DataProviders
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginddt -->
</testsuite> <!-- Test -->
